name: CourtOfJustice
main: com.mcdr.courtofjustice.CourtOfJustice
version: 0.1a
authors: [Erackron, Pyriphlegethon]
softdepend: [Vault]
commands:
  courtofjustice:
    aliases: coj
    description: CourtOfJustice base command
    permission: coj.help
    usage: Type /<command> help for more information
permissions:
  coj.*:
    description: Give access to all CoJ permissions.
    children:
      coj.help: true
      coj.update: true
      coj.judge: true
      coj.jury: true
      coj.spectate: true
    default: op
  coj.help:
    description: Display command uses.
    default: true
  coj.update:
    description: Update CoJ to the latest version and check for updates.
    default: false
  coj.judge:
  	description: Be a judge in a court case.
  	default: false
  coj.jury:
  	description: Be eligible for jury duty.
  	default: true
  coj.spectate:
  	description: Watch a court case in action.
  	default: true